customized data reduction for new data
PYPIT/COS_REDUX pull request #7
Opened 2019-01-11 18:43 UTC by marijana777

Added NUV and FUV customized data reduction for the newest Calcos version (at that time)

2019-01-14 01:24 UTC, profxj requested changes
Just a few changes to work on.

2019-01-14 01:24 UTC, profxj commented on cosredux/science.py
> +def flxwave(fname1, fname2s, xlim=(1900, 1950), ylim=None, norm=True, nseg=0):
Am thinking you should make a new module, e.g. `coadding.py`
and put these methods in there.  Do so if you agree.

2019-01-14 01:24 UTC, profxj commented on cosredux/science.py
> +    spectrasn : list of XSpectrum1D objects
Looks like it comes back as an array instead of a list, agreed?

2019-01-14 01:24 UTC, profxj commented on cosredux/science.py
> +    for i in range(len(spects) - 1):
For future reference, you could have just done:

`for sp in spects[1:]:`

2019-01-14 01:24 UTC, profxj commented on cosredux/science.py
> +def smoothsp(spects, det, snmin):
A rather strange module, but ok..

2019-01-14 01:24 UTC, profxj commented on cosredux/trace.py
> +    if hd['DETECTOR'] == 'FUV':
probably best to use `elif` here and then `else:  raise error`

2019-01-14 01:24 UTC, profxj commented on cosredux/trace.py
> +            x1, x0 = np.polyfit(xfull1, yfull1, 1)
A bit risky to fit without rejection.  One outlier
could give a bad result.

pypeit.utils has a `robust_polyfit` method to consider using.

2019-01-14 01:24 UTC, profxj commented on cosredux/utils.py
> +def findcorrtag(fldpth, verbose=True):
This is quite specific to our ELG program right?

If so, you should have this method in that Repository.

2019-01-20 04:36 UTC, marijana777 commented on cosredux/science.py
> +    spectrasn : list of XSpectrum1D objects
Agreed, and changed the explanation.

2019-01-20 04:36 UTC, marijana777 commented on cosredux/science.py
> +    for i in range(len(spects) - 1):
Changed.

2019-01-20 04:37 UTC, marijana777 commented on cosredux/trace.py
> +    if hd['DETECTOR'] == 'FUV':
Now using elif and else: raise error.

2019-01-20 04:37 UTC, marijana777 commented on cosredux/utils.py
> +def findcorrtag(fldpth, verbose=True):
Now is in the appropriate repository.

2019-01-20 06:11 UTC, marijana777 commented on cosredux/science.py
> +def flxwave(fname1, fname2s, xlim=(1900, 1950), ylim=None, norm=True, nseg=0):
Agreed. Made the new module.

2019-01-20 06:12 UTC, marijana777 commented on cosredux/utils.py
> +def findcorrtag(fldpth, verbose=True):
I also did PR in this repository.

2019-01-20 07:16 UTC, marijana777 commented on cosredux/trace.py
> +            x1, x0 = np.polyfit(xfull1, yfull1, 1)
Now using pypeit.utils.robust_polyfit()

2019-01-20 16:06 UTC, marijana777 commented
@profxj all changes completed.

2019-01-29 19:45 UTC, profxj commented
merging.

2019-01-29 19:46 UTC, merged